timeout: 10
interface_resolution: 1920x1080

/Vale 0.1.0-alpha.1
    comment: Vale x64 for UEFI. Version 0.1.0-alpha.1. Copyright (c) 2026 Luna Dalenuit and contributers, GPL-3.0-or-later.
    protocol: limine
    path: boot():/boot/kernel.elf
    module_path: boot():/boot/initramfs.tar
    module_string: initramfs
    resolution: 1920x1080
