timeout: 10
interface_resolution: 1280x720

/Miyabi 0.1
    comment: Miyabi x64 for UEFI. Version 0.1. Copyright (c) 2026 Luna Delanuit and contributers, GPL-3.0-or-later.
    protocol: limine
    path: boot():/boot/kernel.elf
    module_path: boot():/boot/initramfs.tar
    module_string: initramfs
    resolution: 1280x720
    cmdline: --debug --MOD=/lib/modules/test_module.ko
